### ISSUE TITLE
Running into errors when trying to run ee commands

### ISSUE THREAD

**Issue by Zloka** [digabi/exam-engine#221]
Hi!

I tried following the documentation. I've got both Node.js (v12.8.0) and Firefox installed and I am able to create an exam. However, when trying to run any of the other commands, I get:

```
Error: The module '/usr/local/lib/node_modules/@digabi/exam-engine-cli/node_modules/libxmljs2/build/Release/xmljs.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 72. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:909:18)
    at Module.load (internal/modules/cjs/loader.js:731:32)
    at Function.Module._load (internal/modules/cjs/loader.js:644:12)
    at Module.require (internal/modules/cjs/loader.js:771:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at bindings (/usr/local/lib/node_modules/@digabi/exam-engine-cli/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/usr/local/lib/node_modules/@digabi/exam-engine-cli/node_modules/libxmljs2/lib/bindings.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:868:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:879:10)
    at Module.load (internal/modules/cjs/loader.js:731:32)
```

Have you happened to run into this before?

**Comment by Zloka** [comment]
Tried various commands for rebuilding the module it complains about. 
Seems like `npm install [path] --build-from-source` did the trick.

In my case:
`npm install /usr/local/lib/node_modules/@digabi/exam-engine-cli/node_modules/libxmljs2 --build-from-source`

**Comment by sluukkonen** [comment]
Yep, this is caused by differing node versions. You had run `yarn install` with Node 10.x but were trying to run exam-engine with Node 12.x.
